# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'Old-HCL'
    applications: '2433ac8c-4059-e811-9423-002590ac753d'
    scanname: 'altoro'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'http://demo.testfire.com'
    type: 'production'
    loginMethod: 'None'
    network: 'public'
