name: "HCL AppScan Source Action"
on:
  workflow_dispatch #manually trigger the action 
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run AppScan Source scan
        uses: coadaflorin/source-action@main
        with:
          script-file: simpleIOT/.github/workflows/scan.script   #the name & location of your script file relative to your repo
        env:
            AS_LICENSE_TYPE: 'CLS'
            AS_LICENSE_SERVER_ID: ${{secrets.SERVER_ID}}
            AS_LICENSE_SERVER: ${{secrets.LICENSE_SERVER}}
            AS_INSTALL_MODE: 'standalone'
