name: "HCL AppScan Source Action"
on:
  workflow_dispatch #manually trigger the action 
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run AppScan Source scan
        uses: kjweinert/source-docker@main
        with:
          script-file: appscan_cli.script
        env:
            AS_LICENSE_TYPE: 'CLS'
            AS_LICENSE_SERVER_ID: ${{secrets.SERVER_ID}}
            AS_LICENSE_SERVER: ${{secrets.LICENSE_SERVER}}
            AS_INSTALL_MODE: 'standalone'
      - name: Archive scan results
        uses: actions/upload-artifact@v3
        with:
          name: appscan-source-results
          path: |
            .appscan_source/SimpleIOT.paf.ozasmt
            .appscan_source/scan_report.pdf
