name: "HCL AppScan SAST"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.1
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: 6c058381-17ca-e711-8de5-002590ac753d
          issue_status: "inprogress"
          scan_base_name: "CodeSweep"
          personal_scan: true
      - uses: actions/upload-artifact@v3
        with:
         name: logs
         path: ./*.zip
