name: "HCL AppScan DAST Action"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: self-hosted
    environment: K1
    steps:
      - name: Run ASoC DAST Scan
        uses: karlskorner/forked-dast-action@main
        with:
          baseurl:  https://cloud.appscan.com
          asoc_key: ${{secrets.KARLS_KEY}}
          asoc_secret: ${{secrets.KARLS_SECRET}}
          application_id: bc5951db-9d71-4140-90d0-d6b739f11992
          scan_name: "KARLS_GitHub-Action"
          dynamic_scan_type: dast
          starting_URL: https://demo.testfire.net
          fail_for_noncompliance: false
          wait_for_analysis: false
          network: private
          presence_id: 0dc28465-148b-f111-b337-000d3a7b22dd
