name: "HCL AppScan DAST Action"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: windows-2022
    steps:
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.7
        with:
          baseurl:  https://cloud.appscan.com
          asoc_key: ${{secrets.KARLS_KEY}}
          asoc_secret: ${{secrets.KARLS_SECRET}}
          application_id: 140d8adb-be8b-4d24-a7a0-dce1670c0427
          scan_name: "SES-DAST"
          dynamic_scan_type: dast
          starting_URL: https://sesqa.myhcl.com/
          fail_for_noncompliance: false
          wait_for_analysis: false
          network: private
          presence_id: 0dc28465-148b-f111-b337-000d3a7b22dd
