name: "HCL AppScan DAST Action"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Run ASoC DAST Scan
        uses: karlskorner/forked-dast-action@main
        with:
          baseurl:  https://cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: bc5951db-9d71-4140-90d0-d6b739f11992
          login_sequence_file: ./loginfiles/dast.config
          scan_name: "DAST from GitHub"
          dynamic_scan_type: dast
          starting_URL: ${{vars.STARTING_URL}}
          fail_for_noncompliance: false
          wait_for_analysis: true
          network: private
          presence_id: 8209b0b7-2d87-ef11-8473-000d3a0fc910
