name: "HCL AppScan SAST & SCA Rescan on US DC"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: HCL AppScan SAST on US DC
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.1.0
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          scan_name: ASOC-Test-33/merge-47
          application_id: bc5951db-9d71-4140-90d0-d6b739f11992
          sast_scan_id: baaae2a9-a8d3-46a6-b873-47bf8f0fe687
          sca_scan_id: 61ca15d8-82cc-47e2-a534-2841976bb8cb
          static_analysis_only: true
          wait_for_analysis: true
