name: "HCL AppScan SAST on US DC"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: HCL AppScan SAST on US DC
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.1.0
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: bc5951db-9d71-4140-90d0-d6b739f11992
          static_analysis_only: false
          wait_for_analysis: true
