name: "HCL AppScan SAST on US DC"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: scan bee
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.5
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: d3a522df-bde0-4757-a4a8-b53ac51d707c
          wait_for_analysis: true
