name: "HCL AppScan SAST on US DC"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HCL AppScan SAST on US DC
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@main
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 20ea6185-a151-4147-aeb4-b30b5c1850bc
          sast_scan_id: bc5951db-9d71-4140-90d0-d6b739f11992
          static_analysis_only: true
          wait_for_analysis: true
