name: "HCL AppScan SAST Self-Hosted"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan on self hosted agent
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.1
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 2433ac8c-4059-e811-9423-002590ac753d
          scan_base_name: "ASoC"
          personal_scan: true
      - uses: actions/upload-artifact@v3
        with:
         name: logs
         path: ./*.zip
