name: Chile DAST Scan
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Run ASoC DAST Scan
        run: echo "Building for ${{ inputs.environment_name }}"
