name: "HCL AppScan CodeSweep"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
